### ISSUE TITLE
Integrate styleguidekit-assets-default

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/edition-node-gulp#2]
https://github.com/pattern-lab/styleguidekit-assets-default
- [x] Rename UI menu items to support `pl-pattern-nav-template`
- [x] Rename ishControlsVisible to support `pl-ish-controls-template`
- [x] Write to `patternlab-data.js`
- [x] Navigation not working yet
- [x] Rendering of `pl-ish-controls-template`
- [x] Rendering of `pl-pattern-nav-template`
- [x] Get a local copy of PL PHP v2 running

<h2></h2>

**Reverse engineering** of [this styleguidekit template](https://github.com/pattern-lab/styleguidekit-mustache-default/blob/dev/views/partials/patternSection.mustache) will handle a lot of the work
- [x] [Viewall pages not working](https://github.com/pattern-lab/edition-node-gulp/issues/10)
- [x] [Rendering of `comments` json onto annotations](https://github.com/pattern-lab/edition-node-gulp/issues/3)
- [x] [Lineage is not displaying - key mismatch](https://github.com/pattern-lab/edition-node-gulp/issues/4)
- [x] [HTML tab - output / formatting](https://github.com/pattern-lab/edition-node-gulp/issues/5)
- [x] [Template is not displaying - key mismatch](https://github.com/pattern-lab/edition-node-gulp/issues/6)
- [x] [Pattern State is not displaying - key mismatch](https://github.com/pattern-lab/edition-node-gulp/issues/9)
- [x] [Styleguide Tools > Annotations](https://github.com/pattern-lab/edition-node-gulp/issues/12)
- [x] [Styleguide Tools > Code](https://github.com/pattern-lab/edition-node-gulp/issues/13)
- [x] [Styleguide Tools > Find](https://github.com/pattern-lab/edition-node-gulp/issues/14)
- [x] [Pattern Breadcrumb](https://github.com/pattern-lab/edition-node-gulp/issues/27)

<h2></h2>

- [x] Delete `patternlab_grunt.js` and `patternlab_gulp.js` from core
- [x] **[ONGOING]** Reconcile other ways we've deviated from this styleguide (basePath, default pattern, etc)
  - [Issues being tracked on the spec repo](https://github.com/pattern-lab/the-spec/issues)
- [x ] Unit tests ?
- [x] Cleanup

**Comment by bmuenzenmeyer** [comment]
Making progress on this! 
![image](https://cloud.githubusercontent.com/assets/298435/14231059/d1682112-f939-11e5-8a96-8384025ae65f.png)

**Comment by geoffp** [comment]
Excellent!

**Comment by bmuenzenmeyer** [comment]
Just be aware of the massive rename for keys. Think I got everything but
another glance would be  great.

**Comment by bmuenzenmeyer** [comment]
Got a reference installation of edition-php-development running for v2 on Windows 10 tonight. Should help race toward feature parity on integration of shared repos. 

![image](https://cloud.githubusercontent.com/assets/298435/14450348/2a932db2-0043-11e6-8931-fd538516f9da.png)

Noted tonight that #5 #6 #7 #8 look to be incomplete upstream
